services:
  - type: web
    name: adxpower-api
    runtime: node
    plan: free
    buildCommand: npm install && cd server && ../node_modules/.bin/prisma generate && ../node_modules/.bin/nest build
    startCommand: cd server && ../node_modules/.bin/prisma migrate deploy && node dist/main.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 3000
      - key: CORS_ORIGINS
        value: "*"
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: PAYPAL_MODE
        value: live
      - key: ADMIN_API_KEY
        sync: false
      - key: OFFLINE_SECRET
        sync: false
      - key: NODE_ENV
        value: production
